language: php

php: ["5.3", "5.4", "5.5", "5.6", "hhvm", "hhvm-nightly"]

matrix:
    allow_failures: [{"php": "hhvm"}, {"php": "hhvm-nightly"}]
    fast_finish: true

env:
  global:
    - ARCHER_PUBLISH_VERSION=5.6
    - secure: "OSRh+IiItVmPCiZpvTkpoZ/pcfrsJcHpgTmJFogtqfPst1aAfI9enhTJy2MdHs1Vw2iyx9n0oNBLZ21aHXIh2RrjPbTE5m6XURgPkBRj+jeStMSQiyYGSWuHMdFf4RVubniVVIfVs3qilW0OD6rq6s41ENlaYlWR/RXY1Bwk0jA="

install:
  - ./.travis.install

script:
  - ./vendor/bin/archer travis:build
